### docker-compose-old.yml
### (modified from https://github.com/bitnami/bitnami-docker-kafka)
###
### README:
###
### 1. Update your /etc/hosts with your Docker host IP (ip a show docker0).  Ex:
###
###    172.17.0.1 kafka1.test.local
###    172.17.0.1 kafka2.test.local
###    172.17.0.1 kafka3.test.local
###
### 2. Map the KAFKA_DATA to a folder of your choosing and export it (example):
###
###    $ export KAFKA_DATA=$HOME/Repos/data/kafka
###
### 3. Review https://docs.bitnami.com/tutorials/work-with-non-root-containers/
###
###    mkdir -p $KAFKA_DATA/zookeeper $KAFKA_DATA/kafka1 $KAFKA_DATA/kafka2 $KAFKA_DATA/kafka3
###    sudo chown -R 1001:root $KAFKA_DATA
###

version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ${KAFKA_DATA}/zookeeper:/bitnami/zookeeper
  kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - "9192:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=100
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      ### https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9093,EXTERNAL://kafka1.test.local:9192
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ${KAFKA_DATA}/kafka1:/bitnami/kafka
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - "9292:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=200
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9093,EXTERNAL://kafka2.test.local:9292
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ${KAFKA_DATA}/kafka2:/bitnami/kafka
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:latest'
    ports:
      - "9392:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=300
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9093,EXTERNAL://kafka3.test.local:9392
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ${KAFKA_DATA}/kafka3:/bitnami/kafka
    depends_on:
      - zookeeper