server:
  port: 8080

spring:
  application:
    name: "demo-kafka-producer"
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all   # 0, 1, or all
      compression-type: snappy
      properties:
        "linger.ms": 100
      batch-size: 10000

wavefront:
  application:
    name: ssherwood-demo-kafka-app
    service: ${spring.application.name}